[package]
name = "on-chain-chess-sc-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.on-chain-chess-sc]
path = ".."

[dependencies.multiversx-sc-meta-lib]
version = "0.51.1"
default-features = false
