// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           17
// Async Callback (empty):               1
// Total number of exported functions:  20

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    on_chain_chess_sc
    (
        init => init
        upgrade => upgrade
        isPaused => is_paused
        getWagerTokenId => wager_token_id
        getWagerAmount => wager_amount
        getScore => score
        getIsPlayerWaitingOpt => is_player_waiting_opt
        getGames => games
        getBoard => board
        getDrawOffer => draw_offer
        pause => pause
        unpause => unpause
        setWager => set_wager
        joinGame => join_game
        makeMove => make_move
        draw => draw
        callIllegalMove => call_illegal_move
        signalInactivity => signal_inactivity
        resign => resign
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
